name: GitHub Actions CI
on:
  push:
    paths:
      - "actions/**"
      - ".github/workflows/actions-ci.yml"

concurrency:
  group: actions-ci-${{ github.ref }}
  cancel-in-progress: true

defaults:
  run:
    working-directory: actions

jobs:
  test:
    name: Check
    runs-on: [self-hosted, universal]
    permissions:
      contents: read
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: "16"
          cache: "yarn"
      - run: yarn --frozen-lockfile
      - name: Run tests
        run: make test
      - name: Run Prettier
        run: yarn prettier --check .
      - name: Build all actions
        run: make build
      - name: Check if built version was committed
        run: |
          git diff --quiet --exit-code || (echo "::error::You forgot to commit the built actions, run 'make' locally" && exit 1)
