name: Lambda@Edge CI
on:
  push:
    paths:
      - "edge-lambdas/**"
      - ".github/workflows/edge-lambda-ci.yml"

defaults:
  run:
    working-directory: edge-lambdas

jobs:
  test:
    name: Test
    runs-on: [self-hosted, universal]
    permissions:
      contents: read
    steps:
      - uses: actions/checkout@v2
        with:
          node-version: "16"
          registry-url: "https://npm.pkg.github.com"
          scope: "@pleo-io"
      - name: Install Dependencies
        uses: bahmutov/npm-install@v1
        with:
          working-directory: edge-lambdas
        env:
          NODE_AUTH_TOKEN: ${{ secrets.GH_REGISTRY_NPM_TOKEN }}
      - name: Run tests
        run: make test
